/**
 * GET /api/nudge
 * Returns a single ambient sentence for returning visitors, generated by Claude Haiku.
 */
import { NextRequest, NextResponse } from 'next/server'
import Anthropic from '@anthropic-ai/sdk'
import { getUserProfile } from '@/lib/supabase/server'
import { extractSignals } from '@/lib/inference/signals'

export const runtime = 'nodejs'

const anthropic = new Anthropic()

const rateMap = new Map<string, number[]>()
const RATE_WINDOW_MS = 60_000
const RATE_MAX = 10

function checkRate(ip: string): boolean {
  const now = Date.now()
  const hits = (rateMap.get(ip) ?? []).filter((t) => now - t < RATE_WINDOW_MS)
  if (hits.length >= RATE_MAX) return false
  rateMap.set(ip, [...hits, now])
  return true
}

// In-process cache keyed by signal fingerprint — 30 min TTL
const nudgeCache = new Map<string, { text: string; at: number }>()
const CACHE_TTL = 30 * 60 * 1000

function nudgeFingerprint(signals: ReturnType<typeof extractSignals>): string {
  const topCategory = signals.tasteVector && Object.keys(signals.tasteVector).length > 0
    ? Object.entries(signals.tasteVector).sort(([, a], [, b]) => b - a)[0]?.[0] ?? 'none'
    : signals.categoryInterest[0] ?? 'none'
  return [
    topCategory,
    signals.customerType,
    signals.contentPreference,
    signals.timeOfDay,
    signals.giftContext ? '1' : '0',
    signals.dwellQuality,
    signals.repeatViewedHandles[0] ?? '',
    signals.browseDepth > 20 ? 'deep' : signals.browseDepth <= 3 ? 'early' : 'mid',
  ].join(':')
}

export async function GET(req: NextRequest) {
  const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() ?? 'unknown'
  if (!checkRate(ip)) return new NextResponse('', { status: 200 })

  const sessionId = req.cookies.get('diy_sid')?.value ?? null
  if (!sessionId) return new NextResponse('', { status: 200 })

  const profile = await getUserProfile(sessionId)
  if (!profile) return new NextResponse('', { status: 200 })

  const signals = extractSignals(profile, sessionId)

  // Only nudge returning visitors with at least one strong signal
  if (
    !signals.isReturning ||
    (signals.repeatViewedHandles.length === 0 &&
      signals.categoryInterest.length === 0 &&
      signals.recentSearches.length === 0)
  ) {
    return new NextResponse('', { status: 200 })
  }

  // Check in-process cache
  const fp = nudgeFingerprint(signals)
  const cached = nudgeCache.get(fp)
  if (cached && Date.now() - cached.at < CACHE_TTL) {
    return new NextResponse(cached.text, {
      headers: { 'Content-Type': 'text/plain; charset=utf-8', 'Cache-Control': 'no-store' },
    })
  }

  // Build signal summary
  const lines: string[] = []
  if (signals.repeatViewedHandles.length > 0)
    lines.push(`Returned to ${signals.repeatViewedHandles.length} product(s) more than once`)
  if (signals.categoryInterest.length > 0) {
    const cats = signals.tasteVector
      ? Object.entries(signals.tasteVector)
          .filter(([, c]) => c >= 0.15)
          .sort(([, a], [, b]) => b - a)
          .slice(0, 3)
          .map(([cat, conf]) => `${cat} (${Math.round(conf * 100)}%)`)
          .join(', ')
      : signals.categoryInterest.slice(0, 3).join(', ')
    lines.push(`Category interest: ${cats}`)
  }
  if (signals.recentSearches.length > 0)
    lines.push(`Recent searches: ${signals.recentSearches.slice(-3).join(', ')}`)
  if (signals.customerType === 'buyer')
    lines.push('Has purchased before — familiar, not a first-time visitor')
  if (signals.giftContext) lines.push('Looking for something for someone else')
  if (signals.hasAbandoned) lines.push('Previously added to cart but did not complete purchase')
  if (signals.dwellQuality === 'deep-diver') lines.push('Reads carefully — literary language fits')
  else if (signals.dwellQuality === 'quick-scanner') lines.push('Quick browser — keep it brief and concrete')
  lines.push(`Time: ${signals.timeOfDay}`)

  try {
    const response = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 60,
      system: `You are the ambient voice of DayInDayIn — an art brand by Stine Weirsøe Flamant. Original prints, mugs, tote bags, and apparel. Warm, Scandinavian, personal. When a returning visitor browses, you offer a single quiet observation about what they seem drawn to. Rules: one sentence only, max 18 words, no ellipsis, no exclamation marks, no mention of AI, no sales language. Second person. Warm but understated. Never corporate.`,
      messages: [{
        role: 'user',
        content: `Visitor signals:\n${lines.join('\n')}\n\nWrite one sentence.`,
      }],
    })

    const nudge = response.content[0]?.type === 'text' ? response.content[0].text.trim() : ''
    if (!nudge) return new NextResponse('', { status: 200 })

    nudgeCache.set(fp, { text: nudge, at: Date.now() })

    return new NextResponse(nudge, {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Cache-Control': 'no-store',
        'X-Content-Type-Options': 'nosniff',
      },
    })
  } catch {
    return new NextResponse('', { status: 200 })
  }
}
