/**
 * fix-product-titles.ts
 * Patches the product titles that were wrongly generated by slugToTitle
 * during the rebuild-all-gelato run.
 *
 * Run: npx tsx scripts/fix-product-titles.ts
 */

import * as dotenv from 'dotenv'
import { resolve } from 'path'
dotenv.config({ path: resolve(process.cwd(), '.env.local') })

const DOMAIN = process.env.SHOPIFY_STORE_DOMAIN!

const FIXES: Record<string, string> = {
  'Universe Hole':       'Universe with a Hole',
  'Theres Nothing Here': "There's Nothing Here",
  'Collage Bw':          'Collage (Black & White)',
  'Du Und':              'Du und',
  'Fleur De Lys':        'Fleur de Lys',
  'Green On Blue':       'Green on Blue',
  'Be A Dragon':         'Be a Dragon',
  'View From The Studio':        'View from the Studio',
  'Blue Flower On Green Wood':   'Blue Flower on Green Wood',
  'Red And Green Moss':          'Red and Green Moss',
  'No Ordinary Stone':           'No Ordinary Stone',
  'On The Light Table':          'On the Light Table',
  'Universe Collection':         'Universe Collection',
}

async function getToken(): Promise<string> {
  const res = await fetch(`https://${DOMAIN}/admin/oauth/access_token`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: new URLSearchParams({
      grant_type: 'client_credentials',
      client_id: process.env.SHOPIFY_CLIENT_ID!,
      client_secret: process.env.SHOPIFY_CLIENT_SECRET!,
    }).toString(),
  })
  if (!res.ok) throw new Error(`Token mint failed: ${res.status}`)
  const data = await res.json() as { access_token: string }
  return data.access_token
}
let _tok: string | null = null

async function adminGraphql<T>(query: string, variables: Record<string, unknown> = {}): Promise<T> {
  if (!_tok) _tok = await getToken()
  const res = await fetch(`https://${DOMAIN}/admin/api/2025-01/graphql.json`, {
    method: 'POST',
    headers: { 'X-Shopify-Access-Token': _tok, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query, variables }),
  })
  const json = await res.json() as { data: T; errors?: unknown[] }
  if (json.errors) throw new Error(`GraphQL: ${JSON.stringify(json.errors)}`)
  return json.data
}

interface ProductNode { id: string; title: string }

async function getAllProducts(): Promise<ProductNode[]> {
  const products: ProductNode[] = []
  let cursor: string | null = null
  while (true) {
    const data = await adminGraphql<{ products: { edges: { node: ProductNode; cursor: string }[]; pageInfo: { hasNextPage: boolean } } }>(
      `query($first: Int!, $after: String) {
        products(first: $first, after: $after, query: "status:active") {
          edges { node { id title } cursor }
          pageInfo { hasNextPage }
        }
      }`,
      { first: 200, after: cursor }
    )
    const edges = data.products.edges
    for (const { node, cursor: c } of edges) {
      products.push(node)
      cursor = c
    }
    if (!data.products.pageInfo.hasNextPage) break
  }
  return products
}

async function updateTitle(id: string, title: string): Promise<void> {
  await adminGraphql<unknown>(
    `mutation($input: ProductInput!) { productUpdate(input: $input) { product { id } } }`,
    { input: { id, title } }
  )
}

async function main() {
  console.log('Fetching all products...')
  const products = await getAllProducts()
  console.log(`  ${products.length} active products\n`)

  let fixed = 0
  for (const p of products) {
    const correct = FIXES[p.title]
    if (!correct) continue
    process.stdout.write(`  "${p.title}" → "${correct}"... `)
    await updateTitle(p.id, correct)
    console.log('✓')
    fixed++
    await new Promise(r => setTimeout(r, 300))
  }

  console.log(`\nDone. ${fixed} titles fixed.`)
}

main().catch(err => { console.error(err); process.exit(1) })
